# Generated by Django 3.1.3 on 2020-11-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20201104_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
