# Generated by Django 3.1.3 on 2020-11-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_thread_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
